### ISSUE TITLE
Does it work with SSAS?

### ISSUE THREAD

**Issue by badunc** [spaghettidba/XESmartTarget#10]
I have an Analysis Services session running in SQL 2019 and I can view the live data.  When I attempt to run XESmartTarget with a TableAppenderResponse I get this error:

Error - XESmartTarget.Core.Target : System.InvalidOperationException: Unable to connect to the Extended Events session Cube_Actions on server FLJX1VMTBI03 ---> System.Data.SqlClient.SqlException: The Extended Events session named "Cube_Actions" could not be found. Make sure the session exists and is started.

Is XESmartTarget looking for the session on the database engine?  Can I tell it to look in Analysis Services?

**Comment by spaghettidba** [comment]
Sorry, XESmartTarget does not work with Analysis Services sessions
