### ISSUE TITLE
New-DbaXESmartTableWriter not writing to table

### ISSUE THREAD

**Issue by datadill** [spaghettidba/XESmartTarget#11]
I have been messing around with New-DbaXESmartTableWriter lately and noticed sometimes it works perfectly as expected and other times it will not write to the table at all.  I have been trying different variations of the command I am running in powershell and have found the results to be very inconsistent of whether or not it will actually create/write to a table.  Are there any troubleshooting steps I can take to see where the process is failing?

#Create session
Get-DbaXESessionTemplate | Out-GridView -PassThru | Import-DbaXESessionTemplate -SqlInstance myServer

#Start session
Start-DbaXESession -SqlInstance myServer -Session 'Failing Queries'

#Define table create 
$response = New-DbaXESmartTableWriter -SqlInstance myServer -Database myDatabase -Table myTable -AutoCreateTargetTable 

#Start Writing to table
Start-DbaXESmartTarget -SqlInstance myServer -Session 'Failing Queries' -Responder $response

Edit:  When I run Get-DbaXESmartTarget I keep getting "WARNING: [09:04:38][Get-DbaXESmartTarget] Failure | Not enough memory resources are available to complete this operation".  However, there is zero memory pressure that I am seeing.

**Comment by spaghettidba** [comment]
Thanks for reporting the issues.
Unfortunately the powershell functions rely heavily on background jobs and those are a real nightmare to debug. I'm afraid I can't help you there. What I can suggest is to use the $NotAsJob parameter or use XESmartTarget directly.

**Comment by janszedc** [comment]
That fixed my issue!  Do you know if it is possible to run this as a SQL job to have it continually run or if there would be any downside to doing that with the -NotAsJob flag?

I attempted to open the XESmartTarget.sln, but it appears to be incompatible with VS2017/2019.

**Comment by spaghettidba** [comment]
The solution is compatible with both 2017 and 2019, it only contains an extension for building the setup using Wix.
I have no idea what the downsides of running it as a job could be. All I know is that jobs are unreliable and very hard to debug and troubleshoot. What about running XESmartTarget.exe directly, using the json configuration files? That's the recommended method.

**Comment by janszedc** [comment]
Yea when I try to build the project it complains about the Wix setup, but I am not sure why.  If I do manage to get this working does it run in the background or does the .exe have to always be opened?

**Comment by spaghettidba** [comment]
Well, the executable keeps running, but you can run it in a background process.

**Comment by janszedc** [comment]
Is their any performance impact depending on which server you run it from or is that irrelevant?  From what I have read it sounds like the executable would ideally want to be running on the sql server where it would be inserting the records into the table?

**Comment by spaghettidba** [comment]
I would not run it on the same server as the SQL Server instance. Events are streamed to the client and network bandwidth/latency should not be an issue.

**Comment by janszedc** [comment]
Is it recommended to use XE Smart Target over Extended TSQL Collector?  I watched your hour long video that discussed both and it sounded like Extended TSQL Collector was actually preferred, but from the video I couldn't understand the difference.

**Comment by spaghettidba** [comment]
Hi, Extended TSQL Collector is built for collecting data with the DataCollector feature and store data in the Management Datawarehouse. XESmartTarget is not constrained to that architecture and you can do whatever you want with the Extended Events data you are capturing
