### ISSUE TITLE
Error on XESmartTarget ExecuteTSQLResponse 

### ISSUE THREAD

**Issue by cfdiaz** [spaghettidba/XESmartTarget#8]
Hi Gianluca,
the error appear using XESmartTarget ExecuteTSQLResponse 
[Error SmartTarget.docx](https://github.com/spaghettidba/XESmartTarget/files/5139119/Error.SmartTarget.docx)
I did the test to send records to the windows event log, and each time an event is triggered in the session they are multiplied in the windows event log, that is, if an event appears in the session it creates an event in the windows log, if a second event appears in the session 2 appear in the windows log, if a 3 event appears in the session in the windows log 3 appear, could you please review the reason for this error, if necessary I could pay you something for the help. thank you

**Comment by spaghettidba** [comment]
I identified the bug and fixed it. Hope this helps you. Check out the [latest release](https://github.com/spaghettidba/XESmartTarget/releases/latest).
